import SpherePackingBlueprint.Chapters.SpherePackings
import SpherePackingBlueprint.Chapters.PackingsDensity
import SpherePackingBlueprint.Chapters.E8
import SpherePackingBlueprint.Chapters.FourierAnalysis
import SpherePackingBlueprint.Chapters.CohnElkies
import SpherePackingBlueprint.Chapters.ModularForms
import SpherePackingBlueprint.Chapters.MagicFunctions
import SpherePackingBlueprint.Chapters.ModularInequalities
